dist: trusty
language: go

go:
  - 1.6

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y wget
  - sudo apt-get build-dep -y libvirt
  - wget https://libvirt.org/sources/libvirt-1.2.14.tar.gz
  - sudo mkdir -p /usr/src
  - sudo tar xvzf libvirt-1.2.14.tar.gz -C /usr/src
  - pushd /usr/src/libvirt-1.2.14
  - sudo ./configure --prefix=/usr/
  - sudo make
  - sudo make install
  - sudo libvirtd -d
  - popd
  - go get -u github.com/govend/govend
  - govend -v

install:
  - go build .
  - go install
  
deploy:
  provider: releases
  api_key: "464ae24704716c4e610cbf049dbb6f7f8ba688ef"
  file: "libvirtgo"
  skip_cleanup: true
  on:
    tags: true
